Repository YJU-OKURA/project_minori-next-deployment-repo, pull requests merged in 2024-06, with the labels that each got.

#147 クイズプロンプトページのレイアウトとapiリクエスト関数の作成
  package.json
  public/images/quiz/false.png
  public/images/quiz/index.ts
  public/images/quiz/true.png
  public/svgs/quiz/delete.svg
  public/svgs/quiz/index.ts
  public/svgs/quiz/more.svg
  public/svgs/quiz/normal.svg
  public/svgs/quiz/plus.svg
  src/api/apiUtils.ts
  src/api/baseUrl.ts
  src/api/feedback/getCheckRefer.ts
  src/api/quiz/deleteQuiz.ts
  src/api/quiz/getQuizAi.ts
  src/api/quiz/getQuizList.ts
  src/api/quiz/postQuiz.ts
  src/api/quizFeedback/deleteQuizFeedback.ts
  src/api/quizFeedback/getQuizFeedback.ts
  src/api/quizFeedback/postQuizFeedback.ts
  src/api/quizSet/deleteQuizSet.ts
  src/api/quizSet/getQuizSet.ts
  src/api/quizSet/getRate.ts
  src/api/quizSet/getUserQuizInfo.ts
  src/api/quizSet/getUsers.ts
  src/api/quizSet/postMark.ts
  src/api/quizSet/postSetQuiz.ts
  src/app/classes/[cId]/[mId]/components/CalendarModal.tsx
  src/app/classes/[cId]/[mId]/components/CalendarModalCss.css
  src/app/classes/[cId]/[mId]/components/FeedbackContainer.tsx
  src/app/classes/[cId]/[mId]/components/FeedbackKeywordList.tsx
  src/app/classes/[cId]/[mId]/components/ManageContainer.tsx
  src/app/classes/[cId]/[mId]/components/Quiz.tsx
  src/app/classes/[cId]/[mId]/components/QuizContainer.tsx
  src/app/classes/[cId]/[mId]/components/QuizFeedback.tsx
  src/app/classes/[cId]/[mId]/components/QuizList.tsx
  src/app/classes/[cId]/[mId]/components/QuizReport.tsx
  src/app/classes/[cId]/[mId]/components/QuizSet.tsx
  src/app/classes/[cId]/[mId]/components/UserContainer.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/ChatInput.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/PromptChat.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/Storage.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/SubContainer.tsx
  src/app/classes/[cId]/[mId]/page.tsx
  src/app/classes/[cId]/[mId]/quizForm/components/QuizForm.tsx
  src/app/classes/[cId]/[mId]/quizForm/components/QuizPrompt.tsx
  src/app/classes/[cId]/[mId]/quizForm/components/index.ts
  src/app/classes/[cId]/[mId]/quizForm/page.tsx
  src/app/googleLogin/page.tsx
  src/interfaces/navbar/paramsProps.ts
  src/interfaces/quiz/answer.ts
  src/interfaces/quiz/commentary.ts
  src/interfaces/quiz/index.ts
  src/interfaces/quiz/quiz.ts
  src/interfaces/quiz/quizList.ts
  src/interfaces/quiz/result.ts
  src/interfaces/quiz/submitQuiz.ts
  src/interfaces/quiz/users.ts
  yarn.lock
Labels: 🎨 Html&css, 🔨 Refactor, 📬 API, ✨ Feature, ⏰ P2, 🆗 safe

#149 ビデオチャットフロントエンドコードのアップロード
  package.json
  src/api/_class/index.ts
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/ManageSubContainer.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/SubContainer.tsx
  yarn.lock
Labels: 📬 API, ✨ Feature, ⏰ P1

#151 ビデオチャットの基本レイアウトの作成
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
Labels: 🎨 Html&css, ✨ Feature, ⏰ P1, 🆗 safe

#153 TrelloからJiraへの移行に伴うIssueおよびPull Requestテンプレートの更新
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
Labels: 📃 Docs, ⏰ P3

#155 ビデオチャットの実装
  src/app/classes/[cId]/[mId]/components/UserContainer.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/SubContainer.tsx
Labels: 📬 API, ✨ Feature, ⏰ P1, 🆗 safe

#156 使っていない inputの削除
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
Labels: 🎨 Html&css, 🔨 Refactor, ⏰ P2, 🆗 safe

#157 navbarのレイアウトを修正し、Quizコンポーネントにステータスチェックを追加。
  src/api/feedback/getFeedback.ts
  src/api/material/patchMaterial.ts
  src/api/prompts/patchMessage.ts
  src/api/prompts/postPrompt.ts
  src/app/classes/[cId]/[mId]/components/FeedbackKeywordList.tsx
  src/app/classes/[cId]/[mId]/components/FeedbackList.tsx
  src/app/classes/[cId]/[mId]/components/QuizFeedback.tsx
  src/app/classes/[cId]/[mId]/components/QuizList.tsx
  src/app/classes/[cId]/[mId]/components/QuizReport.tsx
  src/app/classes/[cId]/[mId]/components/QuizSet.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/material/MaterialContainer.tsx
  src/components/navbar/material/MaterialList.tsx
  src/interfaces/quiz/users.ts
  src/interfaces/user/ClassUser.ts
Labels: 🔨 Refactor, 📬 API

#159 マイクとカメラをオン/オフする機能の実装
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
Labels: 🔨 Refactor, 📬 API, ✨ Feature, ⏰ P1, 🆗 safe

#160 ユーザーＩＤが確認できなかった現象の改善
  src/app/classes/[cId]/[mId]/components/UserContainer.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
Labels: 🐞 BugFix, 📬 API, ⏰ P1, 🆗 safe

#161 TURNサーバー設定の追加によるWebRTC接続性の向上
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
Labels: 🐞 BugFix, 📬 API, 🌏 Deploy, ⏰ P1, 🆗 safe

#162 不要なコメントを削除し、TURNサーバーのコードを追加
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
Labels: 🔨 Refactor, 📬 API, ⏰ P1, 🆗 safe

#163 不要なビデオタグを削除し、その他のレイアウトを調整
  src/app/classes/[cId]/[mId]/components/Material.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
Labels: 🎨 Html&css, 🔨 Refactor, 📬 API, ⏰ P1, 🆗 safe

#164 出席簿と出席統計ページを追加
  package.json
  public/images/navbar/index.ts
  public/images/navbar/schoolMark.png
  public/svgs/attendance/edit.svg
  public/svgs/attendance/index.ts
  src/api/attendance/getAttendance.ts
  src/api/attendance/getAttendances.ts
  src/api/attendance/postAttendance.ts
  src/app/classes/[cId]/[mId]/components/Attendance.tsx
  src/app/classes/[cId]/[mId]/components/AttendanceCard.tsx
  src/app/classes/[cId]/[mId]/components/AttendanceContainer.tsx
  src/app/classes/[cId]/[mId]/components/ManageContainer.tsx
  src/app/classes/[cId]/[mId]/components/QuizSet.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/components/navbar/material/MaterialContainer.tsx
  src/components/navbar/profile/Profile.tsx
  src/interfaces/_class/index.ts
  src/interfaces/_class/scheduleData.ts
  src/interfaces/attendance/Attendance.ts
  src/interfaces/attendance/AttendanceUser.ts
  src/interfaces/attendance/ClassDate.ts
  src/interfaces/attendance/index.ts
  yarn.lock
Labels: 🎨 Html&css, 📬 API, ✨ Feature, ⏰ P2, 🆗 safe

#165 不足しているapiリクエスト関数ファイルを追加
  src/api/classUser/getClassMember.ts
Labels: 📬 API, ✨ Feature, ⏰ P3, 🆗 safe

#168 レイアウトと関数のバグ修正
  src/api/feedback/getKeywords.ts
  src/app/classes/[cId]/[mId]/components/AttendanceCard.tsx
  src/app/classes/[cId]/[mId]/components/FeedbackKeywordList.tsx
  src/app/classes/[cId]/[mId]/components/QuizList.tsx
  src/app/classes/[cId]/[mId]/components/QuizSet.tsx
  src/components/navbar/material/MaterialContainer.tsx
Labels: 🎨 Html&css, 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#169 クラス参加とメンバーAPI接続、ライブチャット機能を追加
  package.json
  public/svgs/_class/copyButton.svg
  public/svgs/_class/index.ts
  public/svgs/_class/member/admin.svg
  public/svgs/_class/member/assistant.svg
  public/svgs/_class/member/index.ts
  src/api/_class/getClassesRole.ts
  src/api/_class/index.ts
  src/api/chatRoom/URLList.ts
  src/api/chatRoom/getLiveMessages.ts
  src/api/chatRoom/getMessages.ts
  src/api/chatRoom/index.ts
  src/api/chatRoom/postMessage.ts
  src/api/classCode/getVerifySecret.ts
  src/api/classUser/getClassUsers.ts
  src/app/classes/[cId]/[mId]/components/chatComponents/page.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/ManageSubContainer.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/SubContainer.tsx
  src/app/classes/[cId]/components/card/MemberCard.tsx
  src/app/classes/[cId]/components/card/index.ts
  src/app/classes/[cId]/components/member/Member.tsx
  src/app/classes/[cId]/page.tsx
  src/app/classes/components/_class/Main.tsx
  src/app/classes/components/_class/modal/ClassJoin.tsx
  src/app/classes/components/_class/modal/ClassWait.tsx
  src/app/classes/components/card/CardList.tsx
  src/app/classes/components/card/Wait.tsx
  src/interfaces/_class/modal/modalProps.ts
  src/interfaces/user/User.ts
  tsconfig.json
  yarn.lock
Labels: 🎨 Html&css, 🔨 Refactor, 📬 API, ✨ Feature, ⏰ P1

#170 ライブチャットと投稿のデザイン修正
  src/app/classes/[cId]/[mId]/components/chatComponents/page.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/ManageSubContainer.tsx
  src/app/classes/[cId]/components/main/Post.tsx
Labels: 🎨 Html&css, 🔨 Refactor, ⏰ P3, 🆗 safe
