Repository YJU-OKURA/project_minori-next-deployment-repo, pull requests merged in 2024-02, with the labels that each got.

#19 🔨 chore : downgrade version of typescript to v5.1.6
  yuminnk-nextjs-starter/package.json
  yuminnk-nextjs-starter/yarn.lock
Labels: ⚙ Setting, 🐞 BugFix, ⏰ P1

#21 `TOKEN`を`ADMIN_TOKEN`に更新
  .github/workflows/auto-assign.yml
  .github/workflows/openai_code_review.yml
Labels: ⚙ Setting, 🐞 BugFix, ⏰ P3

#23 相対パス使用への変更
  .github/workflows/auto-reviewer.yml
Labels: ⚙ Setting, 🔨 Refactor, ⏰ P3

#24 ディレクトリ構造の変更
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .prettierignore
  .prettierrc.js
  __tests__/__snapshots__/snapshot.js.snap
  __tests__/index.test.tsx
  __tests__/snapshot.js
  commitlint.config.js
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  postcss.config.js
  public/fonts/temp.ttf
  public/images/temp.png
  public/svgs/next.svg
  public/svgs/vercel.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  tsconfig.json
  yarn.lock
  yuminnk-nextjs-starter/README.md
Labels: 🔨 Refactor

#26 Fix/auto assign review update
  .github/auto_assign.yml
  .github/auto_fe_reviewer.yml
  .github/workflows/auto-issue-assign.yml
  .github/workflows/auto-member.yml
  .github/workflows/auto-reviewer.yml
Labels: ⚙ Setting, 🔨 Refactor, 🐞 BugFix, ⏰ P3

#25 GitHub Actionsワークフローの権限とイベントトリガーの更新
  .github/workflows/openai_code_review.yml
Labels: ⚙ Setting, 🐞 BugFix, ⏰ P3

#28 PRテンプレートから不要な部分を削除
  .github/pull_request_template.md
Labels: 📃 Docs, ⏰ P3

#29 GitHub Actionsの自動レビュワーと自動アサインのロジック改善
  .github/workflows/auto-member.yml
Labels: ⚙ Setting, 🔨 Refactor, 🐞 BugFix, ⏰ P3

#34 💄 style : Modify root style in global.css
  src/app/globals.css
Labels: 🎨 Html&css, ⏰ P3

#35 Navbar Componentの作成とイメジ、アイコンの追加でページ移動を改善
  public/images/navbar/index.ts
  public/images/navbar/user.png
  public/svgs/navbar/book.svg
  public/svgs/navbar/door.svg
  public/svgs/navbar/group.svg
  public/svgs/navbar/index.ts
  public/svgs/navbar/moreHoriz.svg
  public/svgs/navbar/moreVert.svg
  public/svgs/navbar/mypage.svg
  public/svgs/navbar/search.svg
  src/app/layout.tsx
  src/components/navbar.tsx
Labels: 🎨 Html&css, ⏰ P2

#42 navbarがサイズによって移動する問題解決
  src/app/layout.tsx
  src/components/navbar.tsx
Labels: 🎨 Html&css, ⏰ P3

#41 GitHub Actionsの自動レビュアー割り当て問題の修正
  .github/auto_assign.yml
  .github/workflows/auto-member.yml
Labels: ⚙ Setting, 🐞 BugFix, 📃 Docs, ⏰ P3

#38 Trelloリンク連動機能の追加によるGitHub課題テンプレートの改善
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: ⚙ Setting, 📃 Docs, ⏰ P3

#40 Trelloリンク連動機能の追加によるGitHub PRテンプレートの改善
  .github/pull_request_template.md
Labels: ⚙ Setting, 📃 Docs, ⏰ P3

#44 PDFビュアー機能の実装
  next.config.js
  package.json
  src/app/layout.tsx
  src/app/prompts/layout.tsx
  src/app/prompts/page.tsx
  yarn.lock
Labels: 🎨 Html&css, ✨ Feature, ⏰ P1

#48 紹介ページ、ログインモーダルcomponentレイアウトの作成
  public/images/login/index.tsx
  public/images/login/logo.png
  public/svgs/intro/MainImg.svg
  public/svgs/intro/index.tsx
  public/svgs/login/google.svg
  public/svgs/login/index.tsx
  public/svgs/login/line.svg
  public/svgs/login/login.svg
  public/svgs/login/yahoo.svg
  src/app/intro/components/login.tsx
  src/app/intro/page.tsx
  src/interfaces/intro.ts
Labels: 🎨 Html&css, ⏰ P2

#53 Dashboard Componentの機能とレイアウトの作成
  src/app/globals.css
  src/components/dashboard/Dashboard.tsx
  src/components/dashboard/TabsMapping.tsx
  src/components/dashboard/index.ts
  src/interfaces/group/dashboardProps.ts
  src/interfaces/group/index.ts
  src/interfaces/group/tabsMappingProps.ts
Labels: 🎨 Html&css, ✨ Feature, ⏰ P1

#52 グループ管理ページのレイアウトの作成
  public/svgs/group/folder.svg
  public/svgs/group/index.ts
  src/app/components/group/Created.tsx
  src/app/components/group/Favorite.tsx
  src/app/components/group/Header.tsx
  src/app/components/group/Invite.tsx
  src/app/components/group/Joined.tsx
  src/app/components/group/Main.tsx
  src/app/components/group/Waiting.tsx
  src/app/components/group/index.ts
  src/app/page.tsx
Labels: 🎨 Html&css, ⏰ P2

#56 Navbarのwidth設定位置の変更と紹介ページでの非表示処理の実装
  public/images/login/google.png
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/components/navbar.tsx
Labels: 🎨 Html&css, ✨ Feature, ⏰ P3

#60 Card Componentのレイアウト作成
  public/images/group/github.png
  public/images/group/index.ts
  public/images/group/seouluni.png
  public/images/group/twayair.png
  public/images/group/wasedauni.png
  public/images/group/yahoo.png
  public/images/group/yeungjin.png
  public/svgs/group/favorite.svg
  public/svgs/group/index.ts
  public/svgs/group/noneFavorite.svg
  src/app/components/card/Card.tsx
  src/app/components/card/Invitation.tsx
  src/app/components/card/index.ts
  src/app/components/group/Created.tsx
  src/app/components/group/Favorite.tsx
  src/app/components/group/Invite.tsx
  src/app/components/group/Joined.tsx
  src/app/components/group/Waiting.tsx
  src/interfaces/group/cardProps.ts
  src/interfaces/group/invitationProps.ts
Labels: 🎨 Html&css, ⏰ P3

#62 イメージのルートをObjectとして管理するようにコードを修正
  public/images/login/google.png
  public/images/login/index.ts
  public/images/login/index.tsx
  public/images/navbar/index.ts
  public/svgs/intro/index.ts
  public/svgs/intro/index.tsx
  public/svgs/login/index.ts
  public/svgs/navbar/index.ts
  src/app/components/group/Header.tsx
  src/app/components/group/Main.tsx
  src/app/components/group/index.ts
  src/app/intro/components/login/Login.tsx
  src/app/intro/components/login/index.ts
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/dashboard/TabsMapping.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/index.ts
Labels: 🔨 Refactor, ⏰ P3

#65 Dashboard Componentのスタイル変更
  src/components/dashboard/Dashboard.tsx
Labels: 🎨 Html&css, ⏰ P3

#67 ログインモーダル終了方法およびログインcomponentのCSS修正
  public/images/login/index.ts
  public/images/login/logo.png
  public/svgs/login/index.ts
  public/svgs/login/logo.svg
  src/app/intro/components/login/Login.tsx
  src/app/intro/page.tsx
  src/interfaces/intro.ts
Labels: 🎨 Html&css, 🔨 Refactor, ⏰ P3
