Repository YJU-OKURA/project_minori-next-deployment-repo, pull requests merged in 2024-04, with the labels that each got.

#103 managePrompt共通レイアウトの作成
  src/app/[className]/[materialName]/components/ManageContainer.tsx
  src/app/[className]/[materialName]/components/ManageMaterialContainer.tsx
  src/app/[className]/[materialName]/components/Material.tsx
  src/app/[className]/[materialName]/components/index.ts
  src/app/[className]/[materialName]/components/manageSubComponents/ManageSubContainer.tsx
  src/app/[className]/[materialName]/page.tsx
  src/styles/variable.css
Labels: 🎨 Html&css, ✨ Feature, ⏰ P3

#106 recoilの適用とGoogleソーシャルログイン機能の追加
  next.config.js
  package.json
  public/gif/eclipse.gif
  public/gif/index.ts
  src/api/apiUtils.ts
  src/api/auth/getGoogleLogin.ts
  src/api/auth/postGoogleLogin.ts
  src/api/baseUrl.ts
  src/api/httpStatus.ts
  src/app/intro/components/login/Login.tsx
  src/app/intro/googleLogin/page.tsx
  src/app/layout.tsx
  src/components/RecoilRootContainer.tsx
  src/hooks/useRecoilStateWithLocalStorage.ts
  src/interfaces/recoilRootContainerProps.ts
  src/interfaces/user/AccessToken.ts
  src/interfaces/user/LoginData.ts
  src/interfaces/user/RefreshToken.ts
  src/interfaces/user/User.ts
  src/interfaces/user/index.ts
  src/recoil/atoms/accessTokenState.ts
  src/recoil/atoms/isLoginState.ts
  src/recoil/atoms/refreshTokenState.ts
  src/recoil/atoms/userState.ts
  yarn.lock
Labels: ⚙ Setting, 🎨 Html&css, 📬 API, ✨ Feature, ⏰ P2

#108 PDFファイル表示機能の実装
  src/app/[className]/[materialName]/components/Material.tsx
  src/app/prompts/layout.tsx
  src/app/prompts/page.tsx
Labels: 📬 API, ✨ Feature, ⏰ P2

#111 Navbar layout修正とapi接続
  src/api/classUser/putUserName.ts
  src/api/material/deleteMaterial.ts
  src/api/material/patchMaterial.ts
  src/api/material/postMaterial.ts
  src/api/material/searchMaterial.ts
  src/api/prompts/postPromptAccess.ts
  src/components/navbar/Navbar.tsx
  src/components/navbar/material/MaterialContainer.tsx
  src/components/navbar/material/MaterialForm.tsx
  src/components/navbar/material/MaterialList.tsx
  src/components/navbar/material/index.ts
  src/components/navbar/profile/EditName.tsx
  src/components/navbar/profile/Profile.tsx
  src/components/warning/Warning.tsx
  src/interfaces/error/errorProps.ts
  src/interfaces/error/index.ts
  src/interfaces/navbar/editProps.ts
  src/interfaces/navbar/formProps.ts
  src/interfaces/navbar/index.ts
  src/interfaces/navbar/paramsProps.ts
  src/model/User.ts
Labels: 🎨 Html&css, 🔨 Refactor, 📬 API, ✨ Feature, ⏰ P2

#112 不足しているinterfaceファイルとimageファイルを追加
  public/svgs/error/error.svg
  public/svgs/error/index.ts
  public/svgs/navbar/index.ts
  public/svgs/navbar/plus.svg
  public/svgs/navbar/prompt/cloud.svg
  public/svgs/navbar/prompt/index.ts
  src/interfaces/navbar/index.ts
Labels: 🔨 Refactor, ⏰ P3

#113 Node環境でwindowオブジェクトの使用によるバグ修正
  .gitignore
  src/components/navbar/Navbar.tsx
Labels: 🔨 Refactor, 🐞 BugFix, ⏰ P3

#114 プロンプトページレイアウトの作成とapi関数の連携
  src/api/feedback/deleteFeedback.ts
  src/api/feedback/getFeedback.ts
  src/api/feedback/getFeedbacks.ts
  src/api/feedback/getKeywords.ts
  src/api/feedback/postFeedback.ts
  src/api/prompts/getMessage.ts
  src/api/prompts/postPrompt.ts
  src/app/[className]/[materialName]/components/FeedbackContainer.tsx
  src/app/[className]/[materialName]/components/FeedbackForm.tsx
  src/app/[className]/[materialName]/components/FeedbackKeywordList.tsx
  src/app/[className]/[materialName]/components/FeedbackList.tsx
  src/app/[className]/[materialName]/components/ManageContainer.tsx
  src/app/[className]/[materialName]/components/UserContainer.tsx
  src/app/[className]/[materialName]/components/subComponents/ChatInput.tsx
  src/app/[className]/[materialName]/components/subComponents/ClassChat.tsx
  src/app/[className]/[materialName]/components/subComponents/PromptChat.tsx
  src/app/[className]/[materialName]/components/subComponents/Storage.tsx
  src/app/[className]/[materialName]/components/subComponents/SubContainer.tsx
  src/app/[className]/[materialName]/page.tsx
  src/interfaces/feedback/feedback.ts
  src/interfaces/feedback/index.ts
  src/interfaces/feedback/keyWord.ts
  src/interfaces/prompt/index.ts
  src/interfaces/prompt/inputProps.ts
  src/styles/variable.css
Labels: 🎨 Html&css, 📬 API, ✨ Feature, ⏰ P2

#116 recoil persistライブラリを追加し、ログイン状態を維持するように修正
  package.json
  src/app/intro/googleLogin/page.tsx
  src/app/layout.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/profile/Profile.tsx
  src/components/protect/Protect.tsx
  src/components/protect/index.ts
  src/recoil/atoms/isLoginState.ts
  src/recoil/atoms/userState.ts
  yarn.lock
Labels: 🎨 Html&css, ✨ Feature, ⏰ P2

#117 ログインロジック修正とログアウト修正
  src/api/apiUtils.ts
  src/app/intro/page.tsx
  src/components/navbar/profile/Profile.tsx
Labels: 🔨 Refactor, 📬 API, ⏰ P3

#118 クラスidを通じたユーザー情報関数の追加及びログイン状態管理の修正
  src/api/apiUtils.ts
  src/api/classUser/getClassInfo.ts
  src/api/prompts/postPrompt.ts
  src/app/[className]/[materialName]/components/subComponents/PromptChat.tsx
  src/app/[className]/[materialName]/components/subComponents/Storage.tsx
  src/app/intro/googleLogin/page.tsx
  src/app/layout.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/material/MaterialContainer.tsx
  src/components/navbar/material/MaterialForm.tsx
  src/components/navbar/material/MaterialList.tsx
  src/components/navbar/profile/Profile.tsx
  src/components/protect/Protect.tsx
  src/components/protect/index.ts
  src/constants/roles.ts
  src/interfaces/user/ClassUser.ts
  src/interfaces/user/index.ts
  src/recoil/atoms/classUserState.ts
  src/recoil/atoms/userState.ts
Labels: 🎨 Html&css, 🔨 Refactor, 📬 API, ✨ Feature, ⏰ P3

#119 materialの状態管理追加 materialコンポーネントの修正
  src/app/[className]/[materialName]/components/subComponents/PromptChat.tsx
  src/app/[className]/[materialName]/components/subComponents/Storage.tsx
  src/app/[className]/[materialName]/components/subComponents/SubContainer.tsx
  src/app/[className]/[materialName]/page.tsx
  src/components/navbar/material/MaterialList.tsx
  src/interfaces/navbar/material.ts
  src/recoil/atoms/materialState.ts
Labels: 🔨 Refactor, ✨ Feature, ⏰ P3

#121 materialコンポーネントとnavbarコンポーネントのpropsとapi関数を修正
  src/api/classUser/getClassInfo.ts
  src/api/feedback/getFeedback.ts
  src/api/material/patchMaterial.ts
  src/api/prompts/postPrompt.ts
  src/app/Loading.tsx
  src/app/[className]/[materialName]/components/FeedbackContainer.tsx
  src/app/[className]/[materialName]/components/FeedbackForm.tsx
  src/app/[className]/[materialName]/components/FeedbackKeywordList.tsx
  src/app/[className]/[materialName]/components/Material.tsx
  src/app/[className]/[materialName]/components/subComponents/SubContainer.tsx
  src/app/[className]/[materialName]/page.tsx
  src/app/layout.tsx
  src/components/footer/Footer.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/material/MaterialContainer.tsx
  src/components/navbar/material/MaterialForm.tsx
  src/components/navbar/material/MaterialList.tsx
  src/components/navbar/profile/Profile.tsx
  src/interfaces/navbar/formProps.ts
Labels: 🎨 Html&css, 🔨 Refactor, 📬 API, ⏰ P2

#124 MaterialコンポーネントのCSSを修正
  src/app/[className]/[materialName]/components/Material.tsx
Labels: 🎨 Html&css, 🥰 Accessibility, 🔨 Refactor, ⏰ P2

#125 発表前の英文をハングルに変更する作業
  src/app/[className]/[materialName]/components/FeedbackContainer.tsx
  src/app/[className]/[materialName]/components/FeedbackForm.tsx
  src/app/[className]/[materialName]/components/FeedbackList.tsx
  src/app/[className]/[materialName]/components/Quiz.tsx
  src/app/[className]/[materialName]/components/UserContainer.tsx
  src/app/[className]/[materialName]/page.tsx
  src/app/[className]/components/card/PostCard.tsx
  src/app/[className]/components/card/ScheduleCard.tsx
  src/app/[className]/components/main/Main.tsx
  src/app/[className]/components/main/Notice.tsx
  src/app/[className]/components/main/Post.tsx
  src/app/[className]/components/main/Schedule.tsx
  src/app/[className]/components/modal/ClassCreatePost.tsx
  src/app/[className]/components/modal/ClassCreateSchedule.tsx
  src/app/[className]/components/modal/ClassPost.tsx
  src/app/[className]/page.tsx
  src/app/components/_class/Main.tsx
  src/app/components/_class/modal/ClassCreate.tsx
  src/app/intro/components/login/Login.tsx
  src/app/intro/page.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/material/MaterialContainer.tsx
  src/components/navbar/material/MaterialForm.tsx
  src/components/navbar/material/MaterialList.tsx
  src/components/navbar/profile/EditName.tsx
  src/components/navbar/profile/Profile.tsx
Labels: 🔨 Refactor, ⏰ P3

#129 ログインページの最適化
  next.config.js
  src/app/components/login/Login.tsx
  src/app/page.tsx
Labels: 🎨 Html&css, 🔨 Refactor, 🐞 BugFix, ⏰ P3
