Repository YJU-OKURA/project_minori-next-deployment-repo, pull requests merged in 2024-11, with the labels that each got.

#181 🎨 ビデオチャット: P2P方式からSFU方式(MediaSoup)へのマイグレーション
  package.json
  src/app/classes/[cId]/[mId]/components/manageSubComponents/ConnectionStatus.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/ControlButtons.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/manageSubComponents/VideoBox.tsx
  yarn.lock
Labels: ⚙ Setting, 🔨 Refactor, 🌏 Deploy, ⏰ P1, 🆗 safe

#182 🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🔨 Refactor, 🐞 BugFix, 🌏 Deploy, ⏰ P1, 🆗 safe

#183 🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🔨 Refactor, 🐞 BugFix, 🌏 Deploy, ⏰ P1, 🆗 safe

#184 🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🔨 Refactor, 🐞 BugFix, 🌏 Deploy, ⏰ P1, 🆗 safe

#185 🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🔨 Refactor, 🐞 BugFix, 🌏 Deploy, ⏰ P1, 🆗 safe

#186 🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🔨 Refactor, 🐞 BugFix, 🌏 Deploy, ⏰ P1, 🆗 safe

#187 🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🔨 Refactor, 🐞 BugFix, 🌏 Deploy, ⏰ P1, 🆗 safe

#188 🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🔨 Refactor, 🐞 BugFix, 🌏 Deploy, ⏰ P1, 🆗 safe

#192 attendanceページのエラー修正とLINEソーシャルログイン機能の追加、APIのアップデート
  next.config.js
  public/gif/index.ts
  public/gif/loading.gif
  src/api/attendance/getAttendance.ts
  src/api/attendance/getAttendances.ts
  src/api/attendance/postAttendance.ts
  src/api/auth/getLineLogin.ts
  src/api/auth/postLogin.ts
  src/api/classUser/getClassInfo.ts
  src/api/classUser/getUserInfo.ts
  src/app/classes/[cId]/[mId]/components/Attendance.tsx
  src/app/classes/[cId]/[mId]/components/AttendanceCard.tsx
  src/app/classes/[cId]/[mId]/components/AttendanceContainer.tsx
  src/app/classes/[cId]/[mId]/components/ManageContainer.tsx
  src/app/classes/[cId]/[mId]/page.tsx
  src/app/classes/layout.tsx
  src/app/components/login/Login.tsx
  src/app/login/googleLogin/page.tsx
  src/app/login/layout.tsx
  src/app/login/lineLogin/page.tsx
  src/app/page.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/material/MaterialContainer.tsx
  src/components/navbar/material/MaterialList.tsx
  src/interfaces/attendance/AttendanceData.ts
  src/interfaces/attendance/AttendanceProps.ts
Labels: 🎨 Html&css, 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#193 🛠 ビデオチャットの設定改善：WebSocket と MediaSoup の設定最適化
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  src/app/classes/[cId]/[mId]/components/subComponents/LiveClassViewer.tsx
Labels: 🔨 Refactor, 🐞 BugFix, ✨ Feature, 🌏 Deploy, ⏰ P1, 🆗 safe

#195 🐛 fix: WebSocket再接続ロジックおよび状態管理の改善
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🐞 BugFix, ⏰ P1, 🆗 safe

#196 🐛 fix: WebSocket再接続ロジックおよび状態管理の改善
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🐞 BugFix, ⏰ P1, 🆗 safe

#197 🐛 fix: WebSocket再接続ロジックおよび状態管理の改善
  package.json
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
  yarn.lock
Labels: 🐞 BugFix, ⏰ P1, 🆗 safe

#198 🐛 fix: WebSocket再接続ロジックおよび状態管理の改善
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🐞 BugFix, ⏰ P1, 🆗 safe

#199 🐛 fix: WebSocket再接続ロジックおよび状態管理の改善
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🐞 BugFix, ⏰ P1, 🆗 safe

#200 🐛 fix: WebSocket再接続ロジックおよび状態管理の改善
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🐞 BugFix, ⏰ P1, 🆗 safe

#202 🐛 fix: WebSocket再接続ロジックおよび状態管理の改善
  src/app/classes/[cId]/[mId]/components/manageSubComponents/LiveClass.tsx
Labels: 🐞 BugFix, ⏰ P1, 🆗 safe
