Repository YJU-OKURA/project_minori-next-deployment-repo, pull requests merged in 2024-05, with the labels that each got.

#136 ビルド前に使わないコードの整理
  src/api/_class/index.ts
  src/api/_class/patchClassRole.ts
  src/api/_class/patchToggleFavoriteClass.ts
  src/api/classSchedule/index.ts
  src/api/classSchedule/patchClassSchedule.ts
  src/app/classes/components/card/Card.tsx
Labels: 🐞 BugFix, ⏰ P1

#135 [MIN-176] DockerfileとCI/CDパイプラインの修正でNext.jsデプロイを改善
  .github/workflows/ci.yml
  Dockerfile
Labels: 🔨 Refactor, 🐞 BugFix, 🌏 Deploy, ⏰ P1, 🆗 safe

#141 [MIN-176] ECSへの自動デプロイをGitHub Actionsで実装
  .github/workflows/cicd.yml
Labels: 🌏 Deploy, ⏰ P1, 🆗 safe

#142 nginx設定のためAPIリクエストアドレスの修正
  src/api/baseUrl.ts
Labels: 🔨 Refactor, 📬 API, 🌏 Deploy, ⏰ P2, 🆗 safe

#143 [MIN-176] Dockerfileの最適化によるNext.jsアプリケーションのビルドおよびランタイム性能の向上
  Dockerfile
Labels: 🔨 Refactor, 🌏 Deploy, ⏰ P2, 🆗 safe

#145 README.mdにディレクトリ構造を追加
  README.md
Labels: 📃 Docs, ⏰ P3
